name: build-dev

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: thk-code-arch/intercom-backend
          event-type: build-intercom-dev
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
